### ISSUE TITLE
Typos and Errors in examples folder

### ISSUE THREAD

**Issue by akelshareif** [typpo/quickchart-python#1]
Within the examples folder, `long_url_example.py` file retrieves a shortened URL instead with `qc.get_short_url()`. Furthermore, the commented-out short URL returns an error page which states `Chart not found`.

**Comment by typpo** [comment]
Hi @akelshareif, the `long_url_example` is named as such because the URL shortener takes a long URL and turns it into a short one.  I agree it would be more aptly named `short_url_example`.

The commented-out short URL is an example output but is not meant to persist forever.  QuickChart short URLs expire after 3-6 months, which is why it returns `Chart not found`.

**Comment by akelshareif** [comment]
Thank you for the clarification regarding the short URL expiration @typpo. As a suggestion, maybe adding a comment within the `long_url_example` file indicating that the short URL displayed is an example and has expired could clarify this for future readers of the file. I also agree that the `long_url_example` would be more aptly named `short_url_example`. Thank you for your time and speedy response. The issue will now be closed.

**Comment by typpo** [comment]
Thanks! I've made both suggested changes.
