### ISSUE TITLE
Maximum chart data exceeded

### ISSUE THREAD

**Issue by grantiago** [typpo/quickchart-python#8]
Hi great module. thank you.
```
RuntimeError: Invalid response code from chart creation endpoint: 400
Chart error: Error: Maximum chart data exceeded (348 points). Please make your chart smaller or request an exception.
``` 
How would I request an exception? I am charting river flows. I get a reading every 15 minutes for a span of 7 days. Which comes out to around 732 points. I've reduced the number of days to 3 -- 347 points. That still gives the maximum chart data error. Below 3 days the chart doesn't show the data in a meaningful way.

**Comment by typpo** [comment]
Hi @grantiago, unfortunately the free tier of quickchart.io is limited to 250 datapoints due to CPU constraints.  I can suggest a few options:
- Reduce your data to around 250 data points, considering a large number of datapoints may not be visually distinct anyway
- Use the self-hosted version of Quickchart (https://github.com/typpo/quickchart)
- Upgrade to the [Professional plan](https://quickchart.io/pricing/) on quickchart.io

**Comment by grantiago** [comment]
I resampled the data and it works perfectly. thank you.
